In [1]:
import numpy as np
import pypianoroll as pr
import pickle

In [3]:
import os
os.chdir('..')

In [4]:
pwd

'/mnt/md1/user_victor/automatic_melody_harmonization'

In [5]:
melody = np.load('./melody_baseline.npy')
chord = np.load('./number_96.npy')
chord_onehot = np.load('./onehot_96.npy')
length = np.load('./length.npy')
weight_chord = np.load('./weight_chord.npy')

melody_data = np.load('./melody_data.npy')
chord_groundtruth = np.load('./chord_groundtruth.npy')

f = open('./tempos', 'rb')
tempos = pickle.load(f)
f.close()
f = open('./downbeats', 'rb')
downbeats = pickle.load(f)
f.close()

In [48]:
print('Data from npz:')
print('melody_data shape',melody_data.shape)
print('chord_groundtruth shape',chord_groundtruth.shape)   # 272 為每 2 beats 取出來的 chord
print('length shape',length.shape)
print('tempos shape',len(tempos))
print('downbeats shape',len(downbeats))
print()
print('Data to one hot:')
print('melody shape',melody.shape) 
print('chord_onehot shape',chord_onehot.shape)
print('weight_chord shape',weight_chord.shape)
print('Data to midi number:')
print('chord shape',chord.shape)


Data from npz:
melody_data shape (17430, 13056, 128)
chord_groundtruth shape (17430, 272, 128)
length shape (17430,)
tempos shape 17430
downbeats shape 17430

Data to one hot:
melody shape (17430, 272, 576)
chord_onehot shape (17430, 272, 96)
weight_chord shape (96,)
Data to midi number:
chord shape (17430, 272, 1)


In [62]:
melody[0][:10,:]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
tempos[0].shape[0]

792

In [7]:
path = '../lead-sheet-dataset/datasets/pianoroll/x/x-ambassadors/unsteady/intro.npz'
# data = np.load(path)
data = pr.Multitrack(path)

In [38]:
print('name:',data.name)
print('resolution:',data.beat_resolution)
print('downbeat shape:',data.downbeat.shape)
print('tempo:',data.tempo[0])
print('melody shape:',data.tracks[0].pianoroll.shape)
print('chord shape:',data.tracks[1].pianoroll.shape)

name: unknown
resolution: 24
downbeat shape: (408,)
tempo: 58.00009860016762
melody shape: (408, 128)
chord shape: (408, 128)


In [1]:
a = None

In [7]:
a is not None

False

In [10]:
np.asarray([0])

array([0])

In [11]:
np.array([0])

array([0])

In [16]:
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3), 'constant', constant_values=(0, 6))

array([0, 0, 1, 2, 3, 4, 5, 6, 6, 6])

In [17]:
a

[1, 2, 3, 4, 5]